//--회원가입 - 성공
POST http://localhost:4000/api/user/sign-up HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email":"테스트@mail.com",
  "password":"1234",
  "name":"테스트",
  "confirmPassword":"1234"
}
###
//--로그인 -성공
POST http://localhost:4000/api/user/log-in HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email":"테스트@mail.com",
  "password":"1234"
}
####
//--비밀번호 수정 
PATCH  http://localhost:4000/api/user/user-info HTTP/1.1
Content-Type: application/json; charset=utf-8

{
"password":"1234",
"newPassword":"test",
"confirmPassword":"test"
}

###
//--로그아웃
POST http://localhost:4000/api/user/log-out HTTP/1.1
Content-Type: application/json; charset=utf-8

###
//--회원탈퇴
DELETE  http://localhost:4000/api/user/localhost:4000/api/user/user-info HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "password":"1234"
}
####
//--계정 조회
GET  http://localhost:4000/api/user/user-info HTTP/1.1
Content-Type: application/json; charset=utf-8